# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MESkByKpADI-j65XGLiwUhDNzqSMndZ
"""

import statistics
from collections import Counter

# ─────────────────────────────────────────
#  HELPER FUNCTIONS
# ─────────────────────────────────────────

def get_number(prompt: str) -> float:
    """Prompt user and type-cast input to float."""
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("  ⚠  Invalid input. Please enter a number.\n")

def get_numbers_list() -> list[float]:
    """Collect a list of numbers from the user."""
    print("\n  Enter numbers one by one. Type 'done' when finished.")
    nums: list[float] = []
    while True:
        raw = input(f"  Number [{len(nums)+1}]: ").strip()
        if raw.lower() == "done":
            if len(nums) < 1:
                print("  ⚠  Enter at least one number.")
                continue
            return nums
        try:
            nums.append(float(raw))
        except ValueError:
            print("  ⚠  Invalid input. Try again.")

def divider():
    print("─" * 42)

def header(title: str):
    divider()
    print(f"  {title}")
    divider()


# ─────────────────────────────────────────
#  BASIC ARITHMETIC
# ─────────────────────────────────────────

def basic_arithmetic():
    header("BASIC ARITHMETIC  ( +  −  ×  ÷ )")
    a = get_number("  Enter first number  : ")
    print("  Operations: 1) Add  2) Subtract  3) Multiply  4) Divide")
    op = input("  Choose operation [1-4]: ").strip()

    ops = {"1": "+", "2": "-", "3": "*", "4": "/"}
    if op not in ops:
        print("  ⚠  Invalid choice.")
        return

    b = get_number("  Enter second number : ")

    if op == "4" and b == 0:
        print("\n  ⚠  Cannot divide by zero.")
        return

    symbol = ops[op]
    result: float = eval(f"{a} {symbol} {b}")   # simple & safe — both are floats
    print(f"\n  Result : {a} {symbol} {b} = {result}")


# ─────────────────────────────────────────
#  PERCENTAGE CALCULATORS
# ─────────────────────────────────────────

def percentage_menu():
    header("PERCENTAGE CALCULATOR")
    print("  1) X% of a number          e.g. 20% of 150  → 30")
    print("  2) What % is A of B?       e.g. 30 of 150   → 20%")
    print("  3) % Increase / Decrease   e.g. 100 → 120   → +20%")
    choice = input("  Choose [1-3]: ").strip()

    if choice == "1":
        pct = get_number("  Enter percentage (e.g. 20 for 20%): ")
        num = get_number("  Enter the number                   : ")
        result = (pct / 100) * num
        print(f"\n  Result : {pct}% of {num} = {result}")

    elif choice == "2":
        a = get_number("  Enter value A  : ")
        b = get_number("  Enter total B  : ")
        if b == 0:
            print("  ⚠  B cannot be zero.")
            return
        result = (a / b) * 100
        print(f"\n  Result : {a} is {result:.4f}% of {b}")

    elif choice == "3":
        old = get_number("  Enter original value : ")
        new = get_number("  Enter new value      : ")
        if old == 0:
            print("  ⚠  Original value cannot be zero.")
            return
        change = ((new - old) / abs(old)) * 100
        direction = "increase" if change >= 0 else "decrease"
        print(f"\n  Result : {old} → {new} is a {abs(change):.4f}% {direction}")

    else:
        print("  ⚠  Invalid choice.")


# ─────────────────────────────────────────
#  STATISTICS
# ─────────────────────────────────────────

def statistics_menu():
    header("STATISTICS  ( Mean · Median · Mode · Avg )")
    print("  1) Mean (Average)")
    print("  2) Median")
    print("  3) Mode")
    print("  4) All of the above + Sum, Min, Max")
    choice = input("  Choose [1-4]: ").strip()

    if choice not in ("1", "2", "3", "4"):
        print("  ⚠  Invalid choice.")
        return

    nums = get_numbers_list()
    print()

    if choice == "1" or choice == "4":
        mean = statistics.mean(nums)
        print(f"  Mean (Average) : {mean}")

    if choice == "2" or choice == "4":
        median = statistics.median(nums)
        print(f"  Median         : {median}")

    if choice == "3" or choice == "4":
        freq = Counter(nums)
        max_freq = max(freq.values())
        modes = [k for k, v in freq.items() if v == max_freq]
        if len(modes) == len(set(nums)):
            print(f"  Mode           : No mode (all values appear equally)")
        else:
            print(f"  Mode           : {', '.join(str(m) for m in modes)}"
                  f"  (appears {max_freq}x)")

    if choice == "4":
        print(f"  Sum            : {sum(nums)}")
        print(f"  Min            : {min(nums)}")
        print(f"  Max            : {max(nums)}")
        print(f"  Count          : {len(nums)}")


# ─────────────────────────────────────────
#  MAIN MENU
# ─────────────────────────────────────────

def main():
    print("\n" + "═" * 42)
    print("   PYTHON CALCULATOR")
    print("   Arithmetic · Statistics · Percentage")
    print("═" * 42)

    menu = {
        "1": ("Basic Arithmetic  ( +  −  ×  ÷ )", basic_arithmetic),
        "2": ("Percentage Calculator ( % )",        percentage_menu),
        "3": ("Statistics ( Mean · Median · Mode )", statistics_menu),
        "4": ("Exit",                                None),
    }

    while True:
        print("\n  MAIN MENU")
        for key, (label, _) in menu.items():
            print(f"  {key}) {label}")

        choice = input("\n  Select option [1-4]: ").strip()

        if choice == "4":
            print("\n  Goodbye! 👋\n")
            break
        elif choice in menu:
            print()
            menu[choice][1]()
        else:
            print("  ⚠  Invalid option. Please choose 1–4.")

        input("\n  Press Enter to return to menu...")


if __name__ == "__main__":
    main()